import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>This is my gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <div>
        <h1 className="text-3xl font-bold text-white text-center mt-6 mb-6">This Is My Gallery</h1>
        <p className="text-center inter text-white italic mb-12">
          "A year older <br />A year bolder"
        </p>
        <div className="md:columns-4 columns-2 gap-3 md:w-[1200px] px-4 mx-auto space-y-3 pb-28">
          <div className=" break-inside-avoid">
            <img className="shadow-2xl shadow-[#85aef5] rounded-2xl" src="1.jpg" />
          </div>
          <div className=" break-inside-avoid">
            <img className="shadow-2xl shadow-[#85aef5] rounded-2xl" src="2.jpg" />
          </div>
          <div className=" break-inside-avoid">
            <img className="shadow-2xl shadow-[#85aef5] rounded-2xl" src="3.jpg" />
          </div>
          <div className=" break-inside-avoid">
            <img className="shadow-2xl shadow-[#85aef5] rounded-2xl" src="4.jpg" />
          </div>
          <div className=" break-inside-avoid">
            <img className="shadow-2xl shadow-[#85aef5] rounded-2xl" src="5.jpg" />
          </div>
          <div className=" break-inside-avoid">
            <img className="shadow-2xl shadow-[#85aef5] rounded-2xl" src="6.jpg" />
          </div>
          <div className=" break-inside-avoid">
            <img className="shadow-2xl shadow-[#85aef5] rounded-2xl" src="7.jpg" />
          </div>
          <div className=" break-inside-avoid">
            <img className="shadow-2xl shadow-[#85aef5] rounded-2xl" src="8.jpg" />
          </div>
          <div className=" break-inside-avoid">
            <img className="shadow-2xl shadow-[#85aef5] rounded-2xl" src="9.jpg" />
          </div>
          <div className=" break-inside-avoid">
            <img className="shadow-2xl shadow-[#85aef5] rounded-2xl" src="10.jpg" />
          </div>
        </div>
      </div>
    </>
  );
}
